### ISSUE TITLE
Specify bounds for export

### ISSUE THREAD

**Issue by alexcican** [malkomalko/sketch-android-kit#2]
Hey Rob,

Is there a way to specify like a @bounds layer inside the folder? I want to export two icons of different sizes but I want them to have the same exported size (have empty pixels). It’s like disabling the “trim transparent pixels” option in Sketch. I want to add transparent pixels.

Any ideas? Thanks!

**Comment by bomberstudios** [comment]
Hi there!

This one's for @malkomalko, basically: I recently added this exact same feature to Sketch Generator: https://github.com/bomberstudios/sketch-generator/commit/103b5b9d12fa98dcb1eb88300b767f75f66b001d

Feel free to rip that out : )

**Comment by malkomalko** [comment]
Love it.  I'll work on getting this in as soon as I get some free time.

Cheers!

**Comment by alexcican** [comment]
Awesome, @malkomalko. Nice job, @bomberstudios!

**Comment by alexcican** [comment]
Hey @malkomalko! Any news? If you don’t have time, tell me where I should place the code and I’ll do it :)

**Comment by malkomalko** [comment]
yes, time is getting away from me... if you want to take a crack, just for this repo and give it a whirl :)

**Comment by malkomalko** [comment]
Let me know if this is something that's still needed.  Sorry I totally borked on this.
