### ISSUE TITLE
where is CHPluginsController

### ISSUE THREAD

**Issue by john916zhang** [malkomalko/sketch-android-kit#4]
Oct 22 09:50:59 andersons-iMac.local generate_app (Sketch Plugin)[945]: ReferenceError: Can't find variable: CHPluginsController.
        Plugin “generate_app”, line 617.
        »   [output writeToFile:SETTINGS_FILE atomically:NO] «
Oct 22 09:50:59 andersons-iMac.local Sketch[945]: Exception: {
            line = 617;
            sourceURL = "/Users/anderson/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Android Kit/generate_app.jstalk";
            stack = "global code@/Users/anderson/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Android Kit/generate_app.jstalk:617:38";
        }

**Comment by malkomalko** [comment]
Good morning John.

I'd love to get your help in the near term if you wanted to get this working on 3.1.  I'll add you to the project as a collaborator.  As for the CHPluginsController, they must've taken it out.  It's only used to get the pluginsPath.  There may be a new way to get it.

http://chocolat.googlecode.com/svn/trunk/CHPluginsController.m

As for how I noticed that was even there, go download a tool called http://stevenygard.com/projects/class-dump/ so you can look at the headers inside of Sketch to see what's available.

Hope this helps.
